using CsvHelper.Configuration;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using System.Globalization;
using TuitionCalc.Models;

namespace TuitionCalc.Repositories {
    public interface ITuitionCalcRepository {
        IEnumerable<RawCsvRow> ProcessCSV(Stream importCSV);
        IEnumerable<Family> ProduceJSON(IEnumerable<RawCsvRow> rawRows);
        IEnumerable<Family> CalcTuition(IEnumerable<Family> families);
        byte[] BuildFamiliesPdf(IEnumerable<Family> families);
    }

    public class TuitionCalcRepository : ITuitionCalcRepository {
        public class RawCsvRowMap : ClassMap<RawCsvRow> {
            public RawCsvRowMap() {
                Map(m => m.Family).Name("family");
                Map(m => m.Student).Name("student");
                Map(m => m.Grade).Name("grade");
                Map(m => m.Scholarship).Name("scholarship");
                Map(m => m.RaiseRight).Name("raiseright");
                Map(m => m.TuitionAssistance).Name("tuition assts");
                Map(m => m.WorkerDiscount).Name("worker discount");
                Map(m => m.Miscellaneous).Name("miscellaneous");
                // If any text in field => true
                Map(m => m.Member)
                    .Name("member")
                    .Convert(args => !string.IsNullOrWhiteSpace(args.Row.GetField("member")));
                    // ^^^ Retrieves raw CSV value, checks if it contains ANY text, if so -> true, else false
            }
        }

        public IEnumerable<RawCsvRow> ProcessCSV(Stream importCSV) {
            StreamReader reader = new StreamReader(importCSV);
            using var csv = new CsvHelper.CsvReader(reader, CultureInfo.InvariantCulture);
            csv.Context.RegisterClassMap<RawCsvRowMap>();

            var rawRows = csv.GetRecords<RawCsvRow>().ToList();

            return rawRows;
        }

        public IEnumerable<Family> ProduceJSON(IEnumerable<RawCsvRow> rawRows) {
            var families = new List<Family>();
            Family currentFamily = null;

            foreach (RawCsvRow row in rawRows) {
                if (!string.IsNullOrWhiteSpace(row.Family)) {
                    currentFamily = new Family { FamilyName = row.Family, Students = new List<Student>() };
                    families.Add(currentFamily);
                }

                var student = new Student {
                    Name = row.Student,
                    Grade = row.Grade,
                    Scholarship = row.Scholarship.GetValueOrDefault(), // Sets to 0 if null, otherwise sets to value
                    Member = row.Member,
                    RaiseRight = row.RaiseRight.GetValueOrDefault(),
                    TuitionAssistance = row.TuitionAssistance.GetValueOrDefault(),
                    WorkerDiscount = row.WorkerDiscount.GetValueOrDefault(),
                    Miscellaneous = row.Miscellaneous.GetValueOrDefault(),
                };

                currentFamily.Students.Add(student);
            }

            return families;
        }

        public byte[] BuildFamiliesPdf(IEnumerable<Family> families) {
            var document = Document.Create(container => {
                container.Page(page => {
                    page.Margin(40);

                    page.Header().Text("Tuition Report").FontSize(20).Bold();

                    page.Content().Column(col => {
                        foreach (var family in families) {
                            col.Item().Text(family.FamilyName).FontSize(16).Bold();

                            foreach (var student in family.Students) {
                                col.Item().Text($"{student.Name} - Grade {student.Grade}");
                            }

                            col.Item().Text(""); // spacing
                        }
                    });

                    page.Footer().AlignCenter().Text("Generated by TuitionCalc");
                });
            });

            return document.GeneratePdf();
        }


        public IEnumerable<Family> CalcTuition(IEnumerable<Family> families) {
            return null;
        }
    }
}